export const ON_SET_TEXT_SEARCH_RESULTS_SUCCESS = 'ON_SET_TEXT_SEARCH_RESULTS_SUCCESS';
export const ON_SET_TEXT_SEARCH_RESULTS_FAILED = 'ON_SET_TEXT_SEARCH_RESULTS_FAILED';
export const ON_CLEAR_TEXT_SEARCH_RESULTS = 'ON_CLEAR_TEXT_SEARCH_RESULTS';
export const ON_SET_TEXT_SEARCH_RESULTS_STATUS = 'ON_SET_TEXT_SEARCH_RESULTS_STATUS';

export const ON_SET_SELECTED_FILTERS_SUCCESS = 'ON_SET_SELECTED_FILTERS_SUCCESS';
export const ON_CLEAR_SELECTED_FILTERS = 'ON_CLEAR_SELECTED_FILTERS';
